image: golang:1.11

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/k8s.io
    - /go/src/gopkg.in

build:
  script:
    - ls -lah
    - go mod vendor
    - go build -o kubectl-node_condition main.go
  artifacts:
    paths:
      - kubectl-node_condition
    expire_in: 30 days
